import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'scraped-1',
    name: 'Small Bets - Lifetime Membership',
    creator: 'Daniel Vassallo',
    category: 'Business',
    price: 450,
    sales: 7392,
    revenue: 3326400,
    rating: 4.9,
    reviewCount: 189,
    reviewBreakdown: { stars5: 95, stars4: 2, stars3: 0, stars2: 1, stars1: 2 },
    tags: ['Niche Leader', 'High Revenue', 'Strong Community'],
    aiInsights: 'While overall sentiment is extremely positive, the high upfront price point creates friction for beginner creators seeking low-risk entry into digital business. Competitors can capture market share by offering budget-friendly monthly sub-communities.',
    productUrl: 'https://dvassallo.gumroad.com/l/small-bets'
  },
  {
    id: 'scraped-2',
    name: 'The Good Parts of AWS',
    creator: 'Daniel Vassallo',
    category: 'Education',
    price: 10,
    sales: 15659,
    revenue: 156590,
    rating: 4.7,
    reviewCount: 132,
    reviewBreakdown: { stars5: 85, stars4: 8, stars3: 2, stars2: 1, stars1: 4 },
    tags: ['Niche Leader', 'High Sales'],
    aiInsights: 'While readers appreciate the practical breakdown of core services, some note that it lacks deep coverage of niche AWS features and step-by-step code implementation.',
    productUrl: 'https://dvassallo.gumroad.com/l/aws-good-parts'
  },
  {
    id: '1',
    name: 'Ultimate Notion Life OS',
    creator: 'ProductivityPro',
    category: 'Templates',
    price: 49,
    sales: 12450,
    revenue: 610050,
    rating: 4.8,
    reviewCount: 1420,
    reviewBreakdown: { stars5: 80, stars4: 15, stars3: 3, stars2: 1, stars1: 1 },
    tags: ['Fast Growing', 'Niche Leader'],
    aiInsights: 'Strong market dominance. Consider offering a premium tier with 1-on-1 setup calls. Users frequently request a mobile-optimized layout in reviews.',
    productUrl: 'https://gumroad.com/l/notion-life-os'
  },
  {
    id: '2',
    name: 'SaaS UI Kit - React & Tailwind',
    creator: 'DesignMasters',
    category: 'Design Tools',
    price: 129,
    sales: 850,
    revenue: 109650,
    rating: 4.9,
    reviewCount: 310,
    reviewBreakdown: { stars5: 90, stars4: 8, stars3: 2, stars2: 0, stars1: 0 },
    tags: ['High Revenue'],
    aiInsights: 'Excellent conversion rate but low top-of-funnel traffic. Opportunity to create a free "lite" version or lead-magnet to capture more email leads.',
    productUrl: 'https://gumroad.com/l/saas-ui-kit'
  },
  {
    id: '3',
    name: 'Minimalist Icon Pack',
    creator: 'Iconic Design',
    category: 'Assets',
    price: 19,
    sales: 5200,
    revenue: 98800,
    rating: 3.4,
    reviewCount: 450,
    reviewBreakdown: { stars5: 20, stars4: 25, stars3: 35, stars2: 15, stars1: 5 },
    tags: ['High Sales / Low Rating'],
    aiInsights: 'High demand but poor satisfaction. Reviews indicate missing standard icons (like social media logos) and inconsistent stroke weights. Immediate opportunity for a competitor with better QA.',
    productUrl: 'https://gumroad.com/l/minimalist-icons'
  },
  {
    id: '4',
    name: 'Mastering Next.js 15',
    creator: 'CodeGuru',
    category: 'Education',
    price: 79,
    sales: 2100,
    revenue: 165900,
    rating: 4.7,
    reviewCount: 890,
    reviewBreakdown: { stars5: 75, stars4: 20, stars3: 3, stars2: 1, stars1: 1 },
    tags: ['Consistent'],
    aiInsights: 'Solid educational product. A major opportunity exists to add interactive quizzes or a community Discord, which users are currently building unofficially.',
    productUrl: 'https://gumroad.com/l/mastering-nextjs'
  },
  {
    id: '5',
    name: 'SEO Checklist 2026',
    creator: 'MarketingX',
    category: 'Business',
    price: 29,
    sales: 800,
    revenue: 23200,
    rating: 4.6,
    reviewCount: 150,
    reviewBreakdown: { stars5: 65, stars4: 30, stars3: 3, stars2: 1, stars1: 1 },
    tags: ['Steady Growth'],
    aiInsights: 'Good foundational product. Opportunity to upsell automated SEO auditing tools or a subscription for monthly algorithm updates.',
    productUrl: 'https://gumroad.com/l/seo-checklist'
  },
  {
    id: '6',
    name: '1000+ ChatGPT Prompts',
    creator: 'AI Whisperer',
    category: 'AI Tools',
    price: 15,
    sales: 18500,
    revenue: 277500,
    rating: 3.9,
    reviewCount: 2100,
    reviewBreakdown: { stars5: 35, stars4: 30, stars3: 20, stars2: 10, stars1: 5 },
    tags: ['Volume Leader'],
    aiInsights: 'Massive volume but quality perception is dropping. Many users complain about repetitive prompts. A curated, higher-priced "Pro" version could capture the disgruntled high-end market.',
    productUrl: 'https://gumroad.com/l/chatgpt-prompts-pack'
  }
];
